### ISSUE TITLE
training DQN model on highway-v0

### ISSUE THREAD

**Issue by rjoseph24** [eleurent/highway-env#220] opened 2021-08-17 16:52 UTC
Hi,

I have a question about training a DQN agent from stable-baselines3 on the highway-env. The ego vehicle has to drive on the rightmost lane at the highest speed to maximize it's reward. In my case, it does understand to drive on the right most lane and I might add even at decent speed (not sure if it is the top speed of the vehicle). But it fails to avoid collisions with vehicles in the right lane. I might have trained the model for around a 100,000+ timesteps by now. Any help on this is greatly appreciated.

Regards,
Rohan J

**Comment by eleurent** [comment] 2021-08-23 12:56
Closing this issue as duplicate of https://github.com/eleurent/highway-env/discussions/219

**Closed by eleurent** 2021-08-23 12:56 UTC

**Comment by rjoseph24** [comment] 2021-08-23 13:06
Could you also provide some input to my query on #219 ?
