### ISSUE TITLE
Errors while setting up

### ISSUE THREAD

**Issue by kk2491** [eleurent/highway-env#21] opened 2019-06-13 08:44 UTC
Hi Eleurent,

Thanks for the amazing repository. 

When I was trying to build the project, I ended up in below errors could you please help me to fix.

1. install with Python3 br />
When I try with ```pip3 install --user git+https://github.com/eleurent/highway-env``` I am getting the below error and installation is not successful.

```
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-sir6pe48/matplotlib/
```

2. When I try ```pip install --user git+https://github.com/eleurent/highway-env``` (which does the installation on Python2.7) installation is successful. However I am not able to import the ```highway_env```

```
Python 2.7.12 (default, Nov 12 2018, 14:36:49) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import highway_env
pygame 1.9.4
Hello from the pygame community. https://www.pygame.org/contribute.html
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/kishor/.local/lib/python2.7/site-packages/highway_env/__init__.py", line 2, in <module>
    import highway_env.envs
  File "/home/kishor/.local/lib/python2.7/site-packages/highway_env/envs/__init__.py", line 1, in <module>
    from highway_env.envs.highway_env import *
ImportError: No module named envs.highway_env
>>> 
```

Thank you.

**Comment by eleurent** [comment] 2019-06-13 11:47
Hi @kk2491 
1. I just tried it and could not reproduce the issue:

```
pip3 install --user git+https://github.com/eleurent/highway-env
Collecting git+https://github.com/eleurent/highway-env
  Cloning https://github.com/eleurent/highway-env to /tmp/pip-o35egi6o-build
Requirement already satisfied: gym in /usr/local/lib/python3.6/dist-packages (from highway-env==1.0.dev0)
Requirement already satisfied: numpy in ./.local/lib/python3.6/site-packages (from highway-env==1.0.dev0)
Requirement already satisfied: pygame in /usr/local/lib/python3.6/dist-packages (from highway-env==1.0.dev0)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.6/dist-packages (from highway-env==1.0.dev0)
Requirement already satisfied: pandas in /usr/local/lib/python3.6/dist-packages (from highway-env==1.0.dev0)
Requirement already satisfied: six in /usr/local/lib/python3.6/dist-packages (from gym->highway-env==1.0.dev0)
Requirement already satisfied: pyglet>=1.2.0 in /usr/local/lib/python3.6/dist-packages (from gym->highway-env==1.0.dev0)
Requirement already satisfied: requests>=2.0 in ./.local/lib/python3.6/site-packages (from gym->highway-env==1.0.dev0)
Requirement already satisfied: python-dateutil>=2.1 in /usr/local/lib/python3.6/dist-packages (from matplotlib->highway-env==1.0.dev0)
Requirement already satisfied: pytz in ./.local/lib/python3.6/site-packages (from matplotlib->highway-env==1.0.dev0)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.6/dist-packages (from matplotlib->highway-env==1.0.dev0)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in ./.local/lib/python3.6/site-packages (from matplotlib->highway-env==1.0.dev0)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.6/dist-packages (from matplotlib->highway-env==1.0.dev0)
Requirement already satisfied: future in /usr/local/lib/python3.6/dist-packages (from pyglet>=1.2.0->gym->highway-env==1.0.dev0)
Requirement already satisfied: idna<2.8,>=2.5 in ./.local/lib/python3.6/site-packages (from requests>=2.0->gym->highway-env==1.0.dev0)
Requirement already satisfied: certifi>=2017.4.17 in ./.local/lib/python3.6/site-packages (from requests>=2.0->gym->highway-env==1.0.dev0)
Requirement already satisfied: urllib3<1.24,>=1.21.1 in ./.local/lib/python3.6/site-packages (from requests>=2.0->gym->highway-env==1.0.dev0)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in ./.local/lib/python3.6/site-packages (from requests>=2.0->gym->highway-env==1.0.dev0)
Requirement already satisfied: setuptools in ./.local/lib/python3.6/site-packages (from kiwisolver>=1.0.1->matplotlib->highway-env==1.0.dev0)
Installing collected packages: highway-env
  Running setup.py install for highway-env ... done
Successfully installed highway-env-1.0.dev0
```

Could you try instead:
`pip3 install git+https://github.com/eleurent/highway-env#egg=highway-env`

About point 2., i managed to reproduce the issue, but only on Python 2.7
It seems that it was introduced in 7e108926 and it is related to a difference in how python 2 and 3 manage imports, see: https://stackoverflow.com/a/32658460

I will fix this. However, note that I'm thinking of dropping support for Python 2, so I would advise you to rather investigate the python3 install problem.

**Comment by eleurent** [comment] 2019-06-13 11:55
Actually, maybe your setup tools are out of date.
Run `pip3 install --upgrade setuptools` and try again

**Comment by kk2491** [comment] 2019-06-13 11:56
@eleurent Thanks for the prompt response. 
Update : I am not facing any issues when I use ```virtualenv```. I can run the program seamlessly. Problem must be with my local system. Let me check from my end and update you.

One more question: 
I would like to get more information on ```observation_space``` and ```action_space``` in highway environment. I could see that the ```observation_space``` is Box(25,0) but I am not able to relate the each value to corresponding label. Could you please help me with that.

Thank you
KK

**Comment by kk2491** [comment] 2019-06-13 11:56
> Actually, maybe your setup tools are out of date.
> Run `pip3 install --upgrade setuptools` and try again

I am going to test it right away and update you in a while.

**Comment by kk2491** [comment] 2019-06-13 12:02
> Actually, maybe your setup tools are out of date.
> Run `pip3 install --upgrade setuptools` and try again

I tried this. However it did not fix the issue. Seems like I need to upgrade the ```pip```, if I upgrade pip then I guess it results in some weird issues. 

As of now I am going to stay with virtualenv which is working fine. If I am able to get the fix, will surely let you know. 

Thank you,
KK

**Comment by kk2491** [comment] 2019-06-13 12:03
> @eleurent Thanks for the prompt response.
> Update : I am not facing any issues when I use `virtualenv`. I can run the program seamlessly. Problem must be with my local system. Let me check from my end and update you.
> 
> One more question:
> I would like to get more information on `observation_space` and `action_space` in highway environment. I could see that the `observation_space` is Box(25,0) but I am not able to relate the each value to corresponding label. Could you please help me with that.
> 
> Thank you
> KK

It would be a great help if you could help me with this please. :-)

**Comment by ClementPinard** [comment] 2019-06-13 12:11
error message makes me think there is something wrong with matplotlib. Is it installed on your python3 ? you can either use `pip3 install matplotlib` or `apt install python3-matplotlib`

**Comment by eleurent** [comment] 2019-06-13 12:16
Regarding your question about the observation and action spaces, I agree that it is not properly documented.

The easiest part is the action space. In all environments but `parking-v0`, it is a `Discrete` space with 5 actions whose labels can be accessed by calling `env.ACTIONS` (defined here: https://github.com/eleurent/highway-env/blob/master/highway_env/envs/common/abstract.py#L26)

Then concerning the observation, there exist several types that are defined here: https://github.com/eleurent/highway-env/blob/master/highway_env/envs/common/observation.py

By default, the [KinematicsObservation](https://github.com/eleurent/highway-env/blob/master/highway_env/envs/common/observation.py#L49) is used: it is a fixed-size array where each row stands for a vehicle (1st row is ego vehicle, and the others are the closest vehicles) and each column for a [feature](https://github.com/eleurent/highway-env/blob/master/highway_env/envs/common/observation.py#L53), by default: presence of the vehicle, x and y positions, x and y velocities.
These features are absolute for the ego vehicle, and relative for the others. They are scaled with a non-configurable ratio in the `normalize()` function.

But you could also configure the env to provide a [TimeToCollisionObservation](https://github.com/eleurent/highway-env/blob/master/highway_env/envs/common/observation.py#L20), which is an array of the predicted time to collisions to other vehicles on each lane, assuming constant velocities (several layers for different velocities of the ego-vehicle)

You can change the observation configuration by calling
```
env.configure({"observation": *a config here*})
env.reset()
```
See example configurations [here](https://github.com/eleurent/highway-env/blob/master/highway_env/envs/highway_env.py#L27) and [there](https://github.com/eleurent/highway-env/blob/master/highway_env/envs/two_way_env.py#L25)

I hope that helps

**Comment by eleurent** [comment] 2019-06-13 12:20
By the way, if you have specific needs regarding the observation/action space, feel free to implement your own and create a pull request ;)

**Comment by kk2491** [comment] 2019-06-13 12:33
@eleurent Thank for the quick response. 

My requirement is as below:
1. Reaching the destination is not the priority.
2. Safe manuevers
3. Action spaces I am planning to implement <br /> 
a. Lane Follow 
b. Obstacle Follow
c. Stop 
4. Can I control the obstacle vehicles ?

Thank you

**Comment by kk2491** [comment] 2019-06-13 12:39
@eleurent Is there a way I can completely change the simulator interface. 

Ideally for my requirement I just need a one / two lane road with an obstacle (which is sometimes moving sometimes static)

Thank you

**Comment by eleurent** [comment] 2019-06-13 12:43
As I said, feel free to contribute.

The actions you mention are already partially implemented:
* Lane Follow is enabled by default (the ego-vehicle is an instance of `MDPVehicle`, which is itself a `ControlledVehicle`. The LANE_LEFT and LANE_RIGHT actions (0 and 3) allow you to change the lane being followed
* Obstacle follow and stop: with an MDPVehicle, you directly choose a desired velocity (which is modified by the FASTER and SLOWER) actions. But you could implement another kind of ControlledVehicle and by using the code from the IDMVehicle class (currently used for other vehicles) which contains an Obstacle Following longitudinal controller.

* Can I control the obstacle vehicles ? For now, the action space only allows to control the ego-vehicle. You can specify the behaviours of other vehicles in the highway-env/vehicles/behaviour.py file.
And you can also interact directly with the environment. For instance:
```
env.road.vehicles[2].target_velocity = 0
env.road.vehicles[4].crashed = True
```

**Comment by eleurent** [comment] 2019-06-13 12:46
> Ideally for my requirement I just need a one / two lane road with an obstacle (which is sometimes moving sometimes static)

Static obstacles are defined in highway_env/vehicles/dynamics.py.
If you want something sometimes moving sometimes static, you need to implement this behaviour in a new Vehicle class.

Then, you can create your own environment variant and build the scene that you need. See for example highway_env/envs/merge_env.py

**Comment by kk2491** [comment] 2019-06-13 12:52
@eleurent Thank you so much. This is awesome. I will start implementing and let you know once I have desired output. Please keep this case open for next 7 days. :-)

**Comment by eleurent** [comment] 2019-06-20 14:13
I am closing this issue, feel free to open others if you need help with your contributions.

**Closed by eleurent** 2019-06-20 14:13 UTC
